### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by pd4d10** [koute/pinky#10]
It would be great to have pinky's wasm bundle published at npm. Then web developers could import and use it directly

**Comment by antris** [comment]
In the same vein, I would have liked a precompiled zipped package to just simply include an embedded pinky emulator on my site :)

**Comment by koute** [comment]
Well, sure, I don't see why not, however before I could do something like this the code would have to be refactored a little so that it is actually pluggable into an arbitrary website.

**Comment by nico-abram** [comment]
Why was this closed? :yum: 

I've heard this tool might be useful for publishing to npm https://github.com/rustwasm/wasm-pack
