### ISSUE TITLE
pinky-web stuck at "Loading..." when compiled locally

### ISSUE THREAD

**Issue by Ryan1729** [koute/pinky#6]
I wanted to poke at pinky-web on my own machine, so I cloned `master` and followed the native WebAssembly backend instructions in [the Readme](https://github.com/koute/pinky/blob/master/pinky-web/README.md). The exact nightly I downloaded was `rustc 1.25.0-nightly (616b66dca 2018-02-02)`.

The local server started up just fine, but if I go to `localhost:8000` in a browser that ran the version at http://koute.github.io/pinky-web/ without problems, then I see the description on the left as expected, but on the right I see just "Loading..." instead of the ROM selection menu.

If I open the console on the local version, I see only the single line

```
Finished loading Rust wasm module 'pinky_web'
```

instead of the two lines

```
WebGL support using context: webgl
Finished loading Rust wasm module 'pinky_web'
```

I see at http://koute.github.io/pinky-web/ .

So I suppose something is going wrong with the `wasm` loading somehow?

**Comment by koute** [comment]
Thanks for the report!

It's not working due to the recent changes in nightly Rust; I've just fixed it, so if you'll download newest `cargo-web` it should work.

**Comment by Ryan1729** [comment]
I had to update to `rustc 1.25.0-nightly (3d292b793 2018-02-03)` as well as updating `cargo-web` but it's working perfectly now. Thanks!
