### ISSUE TITLE
Unable to play NESMaker games

### ISSUE THREAD

**Issue by triptych** [koute/pinky#8]
I tried to play the demo NES game from NESMaker
[trollburner_demo.nes.zip](https://github.com/koute/pinky/files/2320821/trollburner_demo.nes.zip)
but it fails saying 
```
Unable to load ROM - unhandled mapper: 30

Sorry about that! Maybe try another ROM?
```
 It would be amazing if this emulator could run NESMaker games!
http://austinmckinley.com/8bit/the-tools.html

**Comment by koute** [comment]
I've added support for mapper 30 since it's completely trivial and added the Troll Burner ROM to the list. (:

**Comment by TheNew8bitHeroes** [comment]
Hey there, Koute - wanted to contact you about possibly using your browser emu for something NESmaker related.  Could you hit me up in an email - joe at TheNew8bitHeroes dot com.  Thanks!
