### ISSUE TITLE
"Load your own ROM" does not work on pinky-web

### ISSUE THREAD

**Issue by blandinw** [koute/pinky#9]
- macOS, issue exists on Firefox and Chrome (at least)
- go to http://koute.github.io/pinky-web/
- Click "Load your own ROM"
- Try to load any file
- See in Javascript console: `TypeError: $1.files is not a function`

**Comment by koute** [comment]
Ah, thanks! I broke this functionality by accident.

Fixed! (: (You might need to force-refresh the page to see the new changes.)
